### ISSUE TITLE
How to catch db fail in moleculer js

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer#1003]
I have developed  two molecule service  . One is Invoice Main . It contain main data of invoice . And also another service called invoice row service it hold all information about invoice row . So according to my requirement user have access to invoice main service only . So within this controller i need to call invoice row service insert method . Then invoice row service persist multiple invoice row data . So i have some problem i need to catch db fails in  Invoice main service . I will show the code snippet below.
       try {
          await ctx.call('invoicerow.insert',{ entities: newinvoiceRows })
            } catch (error) {
             console.log('error',error)
           }
I need  to catch db error with in this catch block .So i have manually change MySQL table column and create error. but console log only display below 
**So i need to know how can i catch Data base error only**
DatabaseError [SequelizeDatabaseError]: Table 'invoice.invoicerows' doesn't exist
    at Query.formatError (/private/var/www/base-fortnox/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)
    at Query.run (/private/var/www/base-fortnox/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /private/var/www/base-fortnox/node_modules/sequelize/lib/sequelize.js:619:16
    at async MySQLQueryInterface.bulkInsert (/private/var/www/base-fortnox/node_modules/sequelize/lib/dialects/abstract/query-interface.js:833:21)
    at async recursiveBulkCreate (/private/var/www/base-fortnox/node_modules/sequelize/lib/model.js:2711:25)
    at async Function.bulkCreate (/private/var/www/base-fortnox/node_modules/sequelize/lib/model.js:2837:12) {
  parent: Error: Table 'invoice.invoicerows' doesn't exist
      at Packet.asError (/private/var/www/base-fortnox/node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (/private/var/www/base-fortnox/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/private/var/www/base-fortnox/node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (/private/var/www/base-fortnox/node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (/private/var/www/base-fortnox/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/private/var/www/base-fortnox/node_modules/mysql2/lib/connection.js:82:25)
      at Socket.emit (events.js:376:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'invoice.invoicerows' doesn't exist",
    sql: "INSERT INTO `invoicerows` (`id`,`invoice_id`,`quantity`,`amount`,`currency`,`description`,`createdAt`,`updatedAt`) VALUES (NULL,11,213,'3.79',1,'','2021-09-07 11:07:15','2021-09-07 11:07:15'),(NULL,11,-23,'230.34',2,'sss','2021-09-07 11:07:15','2021-09-07 11:07:15'),(NULL,11,-10,'56.32',1,'aaaaa','2021-09-07 11:07:15','2021-09-07 11:07:15'),(NULL,11,-10,'10.00',1,'aaaaa','2021-09-07 11:07:15','2021-09-07 11:07:15');",
    parameters: undefined
  },
  original: Error: Table 'invoice.invoicerows' doesn't exist
      at Packet.asError (/private/var/www/base-fortnox/node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (/private/var/www/base-fortnox/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/private/var/www/base-fortnox/node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (/private/var/www/base-fortnox/node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (/private/var/www/base-fortnox/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/private/var/www/base-fortnox/node_modules/mysql2/lib/connection.js:82:25)
      at Socket.emit (events.js:376:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'invoice.invoicerows' doesn't exist",
    sql: "INSERT INTO `invoicerows`

**Comment by icebob** [comment]
It's not related to Moleculer. Search on Google how to catch a specific error type of check the `err.name`
