### ISSUE TITLE
Load service as es6 module

### ISSUE THREAD

**Issue by rhrn** [moleculerjs/moleculer#328]
* api.service.js
```js
import ApiService from 'moleculer-web'

export default {
  name: 'test',
  mixins: [ApiService],
  actions: {
    hello () {
      return 'Hello API Gateway!'
    }
  }
}
```
It's exports as `exports.default`

One of solution override schema by schema.default
```js
if (schema.default) {
  schema = schema.default
}
// schema = schema.default || schema
```
at https://github.com/moleculerjs/moleculer/blob/v0.13.1/src/service-broker.js#L533

**Comment by icebob** [comment]
Could you create a PR with tests?

**Comment by Wallacy** [comment]
Also this can help:
https://www.npmjs.com/package/esm

If used on service-broker ES6 classes should work.

**Comment by tiaod** [comment]
Why this got closed?

**Comment by cs4inctec** [comment]
con confirm that this is still not working.

**Comment by piranna** [comment]
In moleculer 0.14 is still happening. With Typescript default configuration it gets transpiled to CommonJS, but later it can't load EcmaScript Modules dependencies, and when changing its configuration to generate ESM modules I get the next error:

```js
 Failed to load service '/home/piranna/Trabajo/Dyte/dyte-remote-router-provider/dist/services/bootstrap.service.js' Error [ERR_REQUIRE_ESM]: require() of ES Module /home/piranna/Trabajo/Dyte/dyte-remote-router-provider/dist/services/bootstrap.service.js from /home/piranna/Trabajo/Dyte/dyte-remote-router-provider/node_modules/moleculer/src/service-broker.js not supported.
Instead change the require of bootstrap.service.js in /home/piranna/Trabajo/Dyte/dyte-remote-router-provider/node_modules/moleculer/src/service-broker.js to a dynamic import() which is available in all CommonJS modules.
    at ServiceBroker.loadService (/home/piranna/Trabajo/Dyte/dyte-remote-router-provider/node_modules/moleculer/src/service-broker.js:788:14)
    at /home/piranna/Trabajo/Dyte/dyte-remote-router-provider/node_modules/moleculer/src/runner.js:413:50
    at Array.forEach (<anonymous>)
    at MoleculerRunner.loadServices (/home/piranna/Trabajo/Dyte/dyte-remote-router-provider/node_modules/moleculer/src/runner.js:413:25)
    at MoleculerRunner.startBroker (/home/piranna/Trabajo/Dyte/dyte-remote-router-provider/node_modules/moleculer/src/runner.js:485:8)
    at /home/piranna/Trabajo/Dyte/dyte-remote-router-provider/node_modules/moleculer/src/runner.js:504:21
```

How can we load `moleculer` services stored in EcmaScript Modules?
