### ISSUE TITLE
Default unit test passes even when test fails

### ISSUE THREAD

**Issue by shawnlauzon** [moleculerjs/moleculer#392]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Expected Behavior

If I introduce a bug in the generated test (e.g. changing `greeter.hello` to something other than "Hello Moleculer"), the test should fail.

## Current Behavior

The test passes, although the error is printed to the screen.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Modify `greeter.hello` to return something different
2. Run tests
3. See an error but all tests pass.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version:
* NodeJS version: 
* Operating System:

### Failure Logs
```
    console.warn node_modules/bluebird/js/release/debuggability.js:888
      Unhandled rejection Error: expect(received).toBe(expected) // Object.is equality

      Expected: "Hello Moleculer"
      Received: "Hello Molecduler"
          at Object.toBe (/Users/shawn/Development/github/venue-v2/node_modules/expect/build/index.js:172:22)
          at Object.toBe (/Users/shawn/Development/github/venue-v2/test/unit/greeter.spec.js:16:53)
          at Object.asyncJestTest (/Users/shawn/Development/github/venue-v2/node_modules/jest-jasmine2/build/jasmine_async.js:108:37)
          at resolve (/Users/shawn/Development/github/venue-v2/node_modules/jest-jasmine2/build/queue_runner.js:56:12)
          at new Promise (<anonymous>)
          at mapper (/Users/shawn/Development/github/venue-v2/node_modules/jest-jasmine2/build/queue_runner.js:43:19)
          at promise.then (/Users/shawn/Development/github/venue-v2/node_modules/jest-jasmine2/build/queue_runner.js:87:41)
          at <anonymous>

    console.info node_modules/moleculer/src/logger.js:126
      [2018-10-13T13:19:36.029Z] INFO  shawns-macbook-pro.local-28096/BROKER: ServiceBroker is stopped. Good bye.


Test Suites: 2 passed, 2 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        3.368s
Ran all test suites.
```

**Comment by icebob** [comment]
Thanks for your PR!
