### ISSUE TITLE
Error hook does not catch validation error

### ISSUE THREAD

**Issue by alexeymarunin** [moleculerjs/moleculer#462]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ +] I am running the latest version
- [ +] I checked the documentation and found no answer
- [ +] I checked to make sure that this issue has not already been filed
- [ +] I'm reporting the issue to the correct repository

## Expected Behavior
Validation errors are handled in the same manner like usual errors/exceptions in actions.
Error hook handler will catch validation error.

## Current Behavior
Moleculer throws validation error like:
```
ValidationError: Parameters validation error!
```

### Steps to Reproduce
1. create and start broker
2. create service 
3. call service action without required param(s)

### Reproduce code snippet
```js
broker.createService({
  name: 'bar',
   actions: {
     hello: {
       visibility: 'public',
       params: {
         name: {type: 'string'},
       },
       handler(ctx) {
         return 'Hello, ' + ctx.params.name + '!'
       }
     }
   },
   hooks: {
     after: {
       '*': function (ctx, res) {
         return {success: true, data: res}
       }
      },
     error: {
       '*': function (ctx, err) {
         this.logger.error('Houston, we have a problem: ' + err.message)
         return {success: false, error: err.message}
       }
     },
   },
})
// ...
await broker.call('bar.hello', {})
```

### Context

* Moleculer version: 0.13.5
* NodeJS version: 9.10.1
* Operating System: macOS 10.14.2

### Failure Logs
```
[2019-02-06T15:53:52.230Z] INFO  test-node/BROKER: Moleculer v0.13.5 is starting...
[2019-02-06T15:53:52.233Z] INFO  test-node/BROKER: Node ID: test-node
[2019-02-06T15:53:52.234Z] INFO  test-node/BROKER: Namespace: test
[2019-02-06T15:53:52.236Z] INFO  test-node/REGISTRY: Strategy: RoundRobinStrategy
[2019-02-06T15:53:52.239Z] INFO  test-node/BROKER: Serializer: JSONSerializer
[2019-02-06T15:53:52.242Z] INFO  test-node/BROKER: Transporter: TcpTransporter
[2019-02-06T15:53:52.244Z] INFO  test-node/BROKER: Registered 10 internal middleware(s).
[2019-02-06T15:53:52.263Z] INFO  test-node/TRANSIT: Connecting to the transporter...
[2019-02-06T15:53:52.265Z] WARN  test-node/TRANSPORTER: TCP Transporter is an EXPERIMENTAL transporter. Do NOT use it in production yet!
[2019-02-06T15:53:52.284Z] INFO  test-node/TRANSPORTER: TCP server is listening on port 54311
[2019-02-06T15:53:52.290Z] INFO  test-node/TRANSPORTER: UDP Multicast Server is listening on 192.168.1.51:4445. Membership: 239.0.0.0
[2019-02-06T15:53:52.293Z] INFO  test-node/TRANSPORTER: UDP Multicast Server is listening on 10.8.1.26:4445. Membership: 239.0.0.0
[2019-02-06T15:53:52.297Z] INFO  test-node/TRANSPORTER: UDP discovery started.
[2019-02-06T15:53:52.300Z] INFO  test-node/TRANSPORTER: TCP Transporter started.
[2019-02-06T15:53:52.823Z] INFO  test-node/REGISTRY: '$node' service is registered.
[2019-02-06T15:53:52.826Z] INFO  test-node/BROKER: ServiceBroker with 1 service(s) is started successfully.
[2019-02-06T15:53:52.837Z] INFO  test-node/REGISTRY: 'bar' service is registered.
[2019-02-06T15:53:57.847Z] INFO  test-node/TRANSPORTER: UDP discovery stopped.
[2019-02-06T15:53:57.850Z] INFO  test-node/BROKER: ServiceBroker is stopped. Good bye.

ValidationError: Parameters validation error!
    at validateContextParams (node_modules/moleculer/src/validator.js:50:29)
    at ServiceBroker.timeoutMiddleware (node_modules/moleculer/src/middlewares/timeout.js:25:13)
    at ServiceBroker.fallbackMiddleware (node_modules/moleculer/src/middlewares/fallback.js:15:10)
    at ServiceBroker.errorHandlerMiddleware (node_modules/moleculer/src/middlewares/error-handler.js:14:10)
    at ServiceBroker.call (node_modules/moleculer/src/service-broker.js:874:27)
```

**Comment by icebob** [comment]
The problem is that Action hook middleware is in deeper than Validation middleware:
![image](https://user-images.githubusercontent.com/306521/52445236-d4c7de80-2b2a-11e9-909e-edfd6b22ef4d.png)

Maybe would better to swap them. But it can cause breaking change, so it can be implemented in 0.14.

**Comment by alexeymarunin** [comment]
Hi, @icebob 
Thanks for your answer!

It's not big deal (for me), I'm just think that better to handle action errors in one place.

**Comment by icebob** [comment]
Ok, but it can be better because if they are swapped, you can make sanitizations in hooks before validation & handle validation error in error hooks. But it won't able to handle other internal errors, like RequestTimeout, retries, ServiceNotFound...etc.

**Comment by alexeymarunin** [comment]
I think these errors (ServiceNotFound, RequestTimeout) should treat as "external" (for actions) and handle in fallback responses.
Is there the way to handle _all_ such exceptions on sender side? I see "Error handler" circle after "Fallback" in your diagram)

**Comment by kevmt** [comment]
@alexeymarunin @icebob I guess best approach is all error should pass through a dedicated class or central handler? meaning it may be coming from moleculer-db, moleculer-web or nodejs it self. Error reporting is a pain, this was also the case of AdonisJS before. But maybe there are better approach for this as it is microservice not a monolith.

**Comment by icebob** [comment]
The ErrorHandler middleware throws further all errors, it just converts them to MoleculerError and adds Context to the error. So the sender received them.
But at this point, we can implement a "global" broker error handler logic. For example, we can define an `errorHandler(err) {...}` function in the broker options and ErrorHandler middleware can call it.

**Comment by alexeymarunin** [comment]
I like this idea)

**Comment by cantecim** [comment]
That would be excellent

**Comment by mailaneel** [comment]
I also want to add other issues that we are encountering with hooks being before user middlewares

- converting errors throw in hooks (mongoose errors to standard error format)
- handling authorization before hitting hook handlers, current option is adding authorization as mixin for each service

**Comment by mailaneel** [comment]
this is the order we are testing with for middlewares by setting `internalMiddlewares: false` in broker 

```ts
const { Middlewares } = require('moleculer');

const {
  Metrics,
  ErrorHandler,
  Fallback,
  Retry,
  Timeout,
  CircuitBreaker,
  ContextTracker,
  Bulkhead,
  ActionHook,
} = Middlewares;

const middlewares = [
  Metrics(),

  // error handlers and loggers
  ErrorLoggerMiddleware(), // custom logger
  ErrorHandler(), // moleculer
  ErrorHandlerMiddleware(), // custom error handler

  Fallback(),
  Retry(),
  Timeout(),
  CircuitBreaker(),
  ContextTracker(),

  // CACHE (moleculer cache middleware)

  Bulkhead(),

  // VALIDATOR (moleculer params validator)

  // Custom Middlewares / User Middlewares
  TypeDIMiddleware(),
  AuthzMiddleware(),
  ...

  ActionHook(),
].reverse();
```

**Comment by icebob** [comment]
Global `errorHandler` is coming in 0.14.
