### ISSUE TITLE
 demo simple example throwing error because broker.start() missing

### ISSUE THREAD

**Issue by mir-nawaz** [moleculerjs/moleculer#486]
## File
examples/simple/index.js

npm run demo simple

### Fixed code snippet
```js
// Load service
broker.loadService(__dirname + "/../math.service.js");

// Call actions
broker.start()
.then(()=> {
  return broker.call("math.add", { a: 5, b: 3 }).then(res => broker.logger.info("  5 + 3 =", res));
})
```

### Error message 

Unhandled rejection TypeError: Cannot read property 'action' of undefined
    at broker.call.then.then.then.then.then.catch.err (/home/mir/Desktop/workspace/moleculer/examples/simple/index.js:36:59)
    at tryCatcher (/home/mir/Desktop/workspace/moleculer/node_modules/bluebird/js/release/util.js:16:23)

**Comment by icebob** [comment]
Thanks, fixed!
