### ISSUE TITLE
Moleculerjs and moleculer-go compatibility issue

### ISSUE THREAD

**Issue by nnqq** [moleculerjs/moleculer#688]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version _(latest but on v3 protocol - 0.13.13)_
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository _(moleculerjs throws error, but call moleculer-go => moleculers works perfect)_

## Current Behavior

Call **moleculerjs** => **moleculer-go** throws error on **moleculerjs** side. But calling **moleculer-go** => **moleculerjs** works as expected

Console output

```
[2020-03-05T19:44:41.385Z] WARN  imac-denis.local-9788/BROKER: Service 'goMath.add' is not available.
(node:9788) UnhandledPromiseRejectionWarning: ServiceNotAvailableError: Service 'goMath.add' is not available.
    at ServiceBroker.findNextActionEndpoint (/Users/denis/go/src/github.com/nnqq/moleculer-go-and-js/js/node_modules/moleculer/src/service-broker.js:857:13)
    at ServiceBroker.call (/Users/denis/go/src/github.com/nnqq/moleculer-go-and-js/js/node_modules/moleculer/src/service-broker.js:876:25)
    at Timeout._onTimeout (/Users/denis/go/src/github.com/nnqq/moleculer-go-and-js/js/server.js:21:37)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

## Expected Behavior

Expected to get response from **moleculer-go** service

Console output

```
Response from Golang service => 3
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. clone https://github.com/nnqq/moleculer-go-and-js
2. run `make bug`
3. watch for console output

### Reproduce code snippet

Repository https://github.com/nnqq/moleculer-go-and-js

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculerjs version: v0.13.13
* Moleculer-go version: v0.2.1
* NodeJS version: v12.13.1
* Golang version: v1.14
* Operating System: macOS v10.15.3

### Failure Logs
```
[2020-03-05T19:44:41.385Z] WARN  imac-denis.local-9788/BROKER: Service 'goMath.add' is not available.
(node:9788) UnhandledPromiseRejectionWarning: ServiceNotAvailableError: Service 'goMath.add' is not available.
    at ServiceBroker.findNextActionEndpoint (/Users/denis/go/src/github.com/nnqq/moleculer-go-and-js/js/node_modules/moleculer/src/service-broker.js:857:13)
    at ServiceBroker.call (/Users/denis/go/src/github.com/nnqq/moleculer-go-and-js/js/node_modules/moleculer/src/service-broker.js:876:25)
    at Timeout._onTimeout (/Users/denis/go/src/github.com/nnqq/moleculer-go-and-js/js/server.js:21:37)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by nnqq** [comment]
@pentateu Hi. Could it bug on **moleculer-go** side?

**Comment by nnqq** [comment]
I close issue, bug on `moleculer-go` side https://github.com/moleculer-go/moleculer/pull/80
