### ISSUE TITLE
Request is timed out when sending large files

### ISSUE THREAD

**Issue by elixiao** [moleculerjs/moleculer#701]
I create a file service which save stream into local file.

```js
async save(ctx) {
    const {params} = ctx
    const fileWritableStream = fs.createWriteStream(filePath)
    const pipeline = util.promisify(stream.pipeline)
    await pipeline(
      fileStream,
      fileWritableStream
    )
    return {ok:1}
  }
```

when using `call "file.save" --stream  file` to send file, small files are ok to save but large files are not:

```sh
# small files
>> Call 'file.save' with <Stream>. 
>> Execution time:41ms
>> Response:
{ ok: 1 }

# large files 
>> ERROR:
RequestTimeoutError: Request is timed out when call 'file-local.save' action on 'lx-4.local-92259' node.
    at /Users/elixiao/node_modules/moleculer/src/middlewares/timeout.js:42:14
```

and the file service shows:

```
[2020-03-19T11:26:01.039Z] INFO  lx-4.local-92259/REGISTRY: Node 'lx-4.local-92274' connected.
[2020-03-19T11:27:09.666Z] WARN  lx-4.local-92259/TRANSPORTER: NATS client is disconnected.
[2020-03-19T11:27:11.671Z] WARN  lx-4.local-92259/TRANSPORTER: NATS client is reconnecting...
[2020-03-19T11:27:11.714Z] INFO  lx-4.local-92259/TRANSPORTER: NATS client is reconnected.
```

**Comment by artur-krueger** [comment]
Hi, I've encountered the same issue.
The problem is caused by the message size limit of NATS, which is 1M default.
I've already provided a pull request to fix it (https://github.com/moleculerjs/moleculer/pull/683) and it was already merge to master. So it will be available in the next release.
Best, Artur

**Comment by elixiao** [comment]
OK, thank you @artur-krueger . Looking forward to the next release.

**Comment by icebob** [comment]
It will release at this week.

**Comment by support-fdx** [comment]
Still the problem is here on v0.14.5. For Small file [less than 10KB], it is successfully uploaded.

But when i take big size file like [greater than 800KB], 

NATS client is disconnected.

**Comment by elixiao** [comment]
@icebob @artur-krueger It seems the problem still exists after upgrade to version v0.14.6

file service output: 

```sh
2020-04-14T10:38:27.049Z] INFO  lx-4.local-4720/FILE-LOCAL: Service 'file-local' started.
[2020-04-14T10:38:38.522Z] WARN  lx-4.local-4720/TRANSPORTER: NATS client is disconnected.
[2020-04-14T10:38:38.527Z] WARN  lx-4.local-4720/TRANSPORTER: NATS client is reconnecting...
[2020-04-14T10:38:38.864Z] INFO  lx-4.local-4720/TRANSPORTER: NATS client is reconnected.
[2020-04-14T10:38:40.668Z] INFO  lx-4.local-4720/TRANSIT: Put the chunk into pool (size: 0). Seq: 18
[2020-04-14T10:38:42.493Z] INFO  lx-4.local-4720/TRANSIT: Put the chunk into pool (size: 1). Seq: 19
[2020-04-14T10:38:43.527Z] INFO  lx-4.local-4720/TRANSIT: Put the chunk into pool (size: 2). Seq: 20
[2020-04-14T10:38:43.782Z] WARN  lx-4.local-4720/TRANSPORTER: NATS client is disconnected.
[2020-04-14T10:38:43.782Z] WARN  lx-4.local-4720/TRANSPORTER: NATS client is reconnecting...
[2020-04-14T10:38:44.365Z] INFO  lx-4.local-4720/TRANSPORTER: NATS client is reconnected.
[2020-04-14T10:38:45.777Z] INFO  lx-4.local-4720/TRANSIT: Put the chunk into pool (size: 3). Seq: 33
[2020-04-14T10:38:46.027Z] INFO  lx-4.local-4720/TRANSIT: Put the chunk into pool (size: 4). Seq: 34
[2020-04-14T10:38:46.433Z] INFO  lx-4.local-4720/TRANSIT: Put the chunk into pool (size: 5). Seq: 35
[2020-04-14T10:38:46.595Z] INFO  lx-4.local-4720/TRANSIT: Put the chunk into pool (size: 6). Seq: 36
[2020-04-14T10:38:46.595Z] INFO  lx-4.local-4720/TRANSIT: Put the chunk into pool (size: 7). Seq: 37
```

repl output: 

```sh
[2020-04-14T10:40:12.419Z] WARN  lx-4.local-10001/BROKER: Request 'file-local.saveImage' is timed out. { requestID: '6ce2967d-e2aa-4d4f-b864-740e3088f659', nodeID: 'lx-4.local-4720', timeout: 99960.402732 }
>> ERROR:
RequestTimeoutError: Request is timed out when call 'file-local.saveImage' action on 'lx-4.local-4720' node.
    at /Users/lx/job/framework/node_modules/moleculer/src/middlewares/timeout.js:42:14
Data:  { action: 'file-local.saveImage', nodeID: 'lx-4.local-4720' }
```

**Comment by artur-krueger** [comment]
@elixiao Could you please give me some more details, so that I can take a closer look:
- byte size of the data
- configured maxChunkSize (if not default = 256K)
- configuration of max_payload of NATS

**Comment by elixiao** [comment]
@artur-krueger I didn't set NATS max_payload. Maybe that's the reason. I will try it. Thanks!

**Comment by elixiao** [comment]
If the file's max byte size is 5M. Should I set the limit in config file like this?

- moleculer.config.js

```js
transit: {
    maxChunkSize: 5 * 1024 * 1024
}
```

- nats-server.conf

```sh
max_payload: 5242880
```

**Comment by artur-krueger** [comment]
There is some protocol overhead, so maxChunkSize should be a at least bit less than max_payload.

**Comment by artur-krueger** [comment]
@elixiao You don't have to adjust max_payload. It is by default 1M. The chunking feature should ensure that each NATS message will not exceed the max_payload. It does this by splitting too large payloads to several chunks. The default size of maxChunkSize is 256K, so it will not reach max_payload even with the additional protocol overhead.
I'd suggest to keep the default settings on moleculer and NATS side. If it's not working with default settings, please let me know.

**Comment by edurdias** [comment]
@icebob I would recommend re-opening this issue since we had new comments. @elixiao Have you been able to get it working?

**Comment by icebob** [comment]
@edurdias in this case, please provide a repro example.

**Comment by elixiao** [comment]
@edurdias problem still exists. @artur-krueger told me not  to adjust max_payload because:

> It does this by splitting too large payloads to several chunks and maxChunkSize is 256K, so it will not reach max_payload even with the additional protocol overhead.

But it does not work. As you can see, even though I set nats max_payload to 5242880, nats server still crash sometimes.

![image](https://user-images.githubusercontent.com/2291033/94240445-e2bbb480-ff45-11ea-9ec9-01a2e7dce9a2.png)
