### ISSUE TITLE
Cant pass model to other service , when returning this.model

### ISSUE THREAD

**Issue by Mahardika23** [moleculerjs/moleculer#804]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

I'm Currently trying to deploy my moleculer backend app to a K8S cluster, and im using moleculer-db-adapter-sequelize as my Database adapter, My current database design has some relations that relates one a table/database from one service to another service. I need to pass a Sequelize Model to the other service, currently doing it like this : 

![image](https://user-images.githubusercontent.com/52459456/91413906-f952eb00-e875-11ea-99f4-ac07f0032b1d.png)

And then, from the other service i make a relation belongsTo() to that model 

![image](https://user-images.githubusercontent.com/52459456/91413988-18ea1380-e876-11ea-8211-a4ef4d2f2d97.png)

When i run this locally, it works fine, and the model is registered as a Sequelize Model. But when im trying to deploy to a remote kubernetes cluster, the variable 'this.model' is known as "undefined" and the service wouldnt start. 

![image](https://user-images.githubusercontent.com/52459456/91414212-6ebebb80-e876-11ea-9e55-8555a860a8ec.png)

## Expected Behavior

this.model is defined as a Sequelize model when calling from a remote service

## Failure Information

this.model is undefined when calling from remote service. I tried calling other actions remotely and it works fine, so its not a transporter problem.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a moleculer project using moleculer sequelize adapter
2. Create a service ex: regions that has an action getModel() that returns this.model
3. call the action getModel from regions service and define a relation using the regions model.
4. deploy to a remote k8s cluster.
5. check the pods logs, it returns the error above

## regions.service.js
```
"use strict";

const { Op } = require("sequelize");
const DBMixin = require("../../mixins/db.mixin");
const regionModel = require("../../models/master/Regions");
const { response } = require("../../helpers/response");
const seed = require("../../data/master/wilayahv2.json");

module.exports = {
	name: regionModel.name,
	mixins: [DBMixin(regionModel)],
	settings: {
		fields: [
			"kode",
			"name"
		],

		entityValidator: {
		}

	},
	hooks: {
		before: {

		}
	},
	afterConnected: {
	},
	async started() {
		const currentDataCount = await this.model.count();
		if (currentDataCount !== seed.length) {
			this.model.truncate();
			let i, j, temparray, chunk = 12000;
			const regions = seed;
			for (i = 0, j = regions.length; i < j; i += chunk) {
				temparray = regions.slice(i, i + chunk);
				await this.model.bulkCreate(temparray, {
					ignoreDuplicates: true
				});
			}
		}
	},
	actions: {
		getModel() {

			return (this.model);
		},
		getProvinces: {
			rest: "GET /provinces",

			async handler() {
				const provinces = await this.model.findAll({
					where: {
						kode: {
							[Op.like]: "__"
						}
					}
				});
				return response(true, provinces, "null");

			}
		},
		getRegencies: {
			rest: "GET /regencies",
			params: {
				provinceCode: "string|min:2|max:2"
			},
			async handler(ctx) {
				const { params } = ctx;
				const regencies = await this.getRegenciesByProvince(params.provinceCode);
				return response(true, regencies, "null");
			},
		},
		getDistricts: {
			rest: "GET /districts",
			params: {
				regencyCode: "string|min:5|max:5"
			},
			async handler(ctx) {
				const { regencyCode } = ctx.params;

				const districts = await this.getDistrictsByRegency(regencyCode);
				return response(true, districts, "null");
			}
		},
		getVillages: {
			rest: "GET /villages",
			params: {
				districtCode: "string|min:8|max:8"
			},
			async handler(ctx) {
				const { districtCode } = ctx.params;
				const villages = await this.getVillagesByDistricts(districtCode);

				return response(true, villages, "null");
			}
		}


	},
	created() {

	},
	methods: {
		async getAllRegions() {
			const db = this.adapter;
			let regions = await db.find({});
			return regions;
		},
		async getRegenciesByProvince(provinceCode) {
			const regencies = await this.model.findAll({
				where: {
					kode: {
						[Op.like]: `${provinceCode}.__`
					}
				}
			});
			return regencies;
		},
		async getDistrictsByRegency(regencyCode) {
			const villages = await this.model.findAll({
				where: {
					kode: {
						[Op.like]: `${regencyCode}.__`
					}
				}
			});
			return villages;
		},
		async getVillagesByDistricts(districtCode) {
			const villages = await this.model.findAll({
				where: {
					kode: {
						[Op.like]: `${districtCode}.____`
					}
				}
			});
			return villages;
		},
	}
};
```
### customer_address.service.js
```
"use strict";
const DBMixin = require("../../mixins/db.mixin");
const CustomerAddress = require("../../models/CustomerAddress");

module.exports = {
	name: CustomerAddress.name,
	mixins: [DBMixin(CustomerAddress)],
	dependencies: [
		"regions",
		"address_types"
	],
	actions: {
		getModel() {
			return this.model;
		}
	},
	methods: {

	},
	async started() {
		const region = await this.broker.call("regions.getModel");
		const addressType = await this.broker.call("address_types.getModel");
		const test = await this.broker.call("address_types.list");
		console.log(test);
		// this.model.belongsTo(addressType, {
		// 	foreignKey: "addressType"
		// });

			this.model.belongsTo(region, {
			foreignKey: "province",
			as: "region_province"
		});

		this.model.belongsTo(region, {
			foreignKey: "regency",
			as: "region_regency",
		});

		this.model.belongsTo(region, {
			foreignKey: "district",
			as: "region_district"
		});

		this.model.belongsTo(region, {
			foreignKey: "subDistrict",
			as: "region_sub_district"
		});
	}
};
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version:0.14.0
* NodeJS version:  10.19.0
* Operating System: Ubuntu 20.04

### Failure Logs
```

> backend@1.0.0 start /app
> moleculer-runner src/services/**/*.service.js
[2020-08-27T07:51:09.769Z] INFO  customer-address-78b8ff95d7-brsz7-24/BROKER: Moleculer v0.14.8 is starting...
[2020-08-27T07:51:09.771Z] INFO  customer-address-78b8ff95d7-brsz7-24/BROKER: Namespace: tungsten-dev-backend
[2020-08-27T07:51:09.772Z] INFO  customer-address-78b8ff95d7-brsz7-24/BROKER: Node ID: customer-address-78b8ff95d7-brsz7-24
[2020-08-27T07:51:09.773Z] INFO  customer-address-78b8ff95d7-brsz7-24/METRICS: Metrics: Enabled
[2020-08-27T07:51:09.775Z] INFO  customer-address-78b8ff95d7-brsz7-24/METRICS: Metric reporter: PrometheusReporter
[2020-08-27T07:51:09.782Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Strategy: RoundRobinStrategy
[2020-08-27T07:51:09.782Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Discoverer: LocalDiscoverer
[2020-08-27T07:51:09.862Z] INFO  customer-address-78b8ff95d7-brsz7-24/BROKER: Cacher: RedisCacher
[2020-08-27T07:51:09.862Z] INFO  customer-address-78b8ff95d7-brsz7-24/BROKER: Serializer: JSONSerializer
[2020-08-27T07:51:09.869Z] INFO  customer-address-78b8ff95d7-brsz7-24/BROKER: Validator: FastestValidator
[2020-08-27T07:51:09.870Z] INFO  customer-address-78b8ff95d7-brsz7-24/TRACER: Tracing: Enabled
[2020-08-27T07:51:09.870Z] INFO  customer-address-78b8ff95d7-brsz7-24/TRACER: Tracing exporter: ConsoleTraceExporter
[2020-08-27T07:51:09.872Z] INFO  customer-address-78b8ff95d7-brsz7-24/BROKER: Registered 14 internal middleware(s).
[2020-08-27T07:51:09.873Z] INFO  customer-address-78b8ff95d7-brsz7-24/BROKER: Transporter: RedisTransporter
[2020-08-27T07:51:10.438Z] INFO  customer-address-78b8ff95d7-brsz7-24/TRANSIT: Connecting to the transporter...
[2020-08-27T07:51:10.439Z] INFO  customer-address-78b8ff95d7-brsz7-24/TRANSPORTER: Setting Redis transporter
[2020-08-27T07:51:10.441Z] INFO  customer-address-78b8ff95d7-brsz7-24/METRICS: Prometheus metric reporter listening on http://0.0.0.0:3030/metrics address.
[2020-08-27T07:51:10.457Z] INFO  customer-address-78b8ff95d7-brsz7-24/TRANSPORTER: Redis-sub client is connected.
[2020-08-27T07:51:10.457Z] INFO  customer-address-78b8ff95d7-brsz7-24/TRANSPORTER: Setting Redis transporter
[2020-08-27T07:51:10.459Z] INFO  customer-address-78b8ff95d7-brsz7-24/CACHER: Redis cacher connected.
[2020-08-27T07:51:10.462Z] INFO  customer-address-78b8ff95d7-brsz7-24/TRANSPORTER: Redis-pub client is connected.
[2020-08-27T07:51:10.478Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'customer-shareholder-7d5b887b96-snkq9-25' connected.
[2020-08-27T07:51:10.481Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'marital-status-6955f77755-w59rv-24' connected.
[2020-08-27T07:51:10.483Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'country-7d86db57bb-pp2vb-24' connected.
[2020-08-27T07:51:10.485Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'shareholder-type-d86d8444d-zwtwv-24' connected.
[2020-08-27T07:51:10.488Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'marital-status-6955f77755-xtmww-24' connected.
[2020-08-27T07:51:10.490Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'occupation-7868d9df97-blkmj-24' connected.
[2020-08-27T07:51:10.495Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'field-of-work-86489b8656-xvd9k-24' connected.
[2020-08-27T07:51:10.503Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'building-ownership-status-769b8c5b85-9pfv7-24' connected.
[2020-08-27T07:51:10.511Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'total-asset-78d84b8b87-g8gl4-24' connected.
[2020-08-27T07:51:10.525Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'region-756f8f64d8-9dpsz-24' connected.
[2020-08-27T07:51:10.528Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'education-7f47f5fc94-pcvt7-24' connected.
[2020-08-27T07:51:10.532Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'customer-type-69cc76c859-dvsgc-24' connected.
[2020-08-27T07:51:10.536Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'address-type-649648b965-9fkft-24' connected.
[2020-08-27T07:51:10.566Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'region-756f8f64d8-66zsm-24' connected.
[2020-08-27T07:51:10.588Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'shareholder-type-d86d8444d-78dmx-24' connected.
[2020-08-27T07:51:10.616Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'work-experience-74fcb447c6-6rj2c-30' connected.
[2020-08-27T07:51:10.618Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'building-ownership-status-769b8c5b85-r659k-29' connected.
[2020-08-27T07:51:10.620Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'customer-type-69cc76c859-c45c7-24' connected.
[2020-08-27T07:51:10.630Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'field-of-work-86489b8656-rsn5t-25' connected.
[2020-08-27T07:51:10.632Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'api-848b99df56-74hb6-25' connected.
[2020-08-27T07:51:10.634Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'occupation-7868d9df97-9krpv-24' connected.
[2020-08-27T07:51:10.636Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'address-type-649648b965-zhf87-24' connected.
[2020-08-27T07:51:10.649Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'work-experience-74fcb447c6-xqvwf-24' connected.
[2020-08-27T07:51:10.651Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'api-848b99df56-6tvqh-24' connected.
[2020-08-27T07:51:10.657Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'document-type-66c9f89c7-p7b7m-24' connected.
[2020-08-27T07:51:10.662Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'total-asset-78d84b8b87-qsm9k-24' connected.
[2020-08-27T07:51:10.665Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'document-type-66c9f89c7-7gvgc-24' connected.
[2020-08-27T07:51:10.667Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'country-7d86db57bb-hkbgf-24' connected.
[2020-08-27T07:51:10.669Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: Node 'education-7f47f5fc94-z6fcx-24' connected.
[2020-08-27T07:51:10.968Z] INFO  customer-address-78b8ff95d7-brsz7-24/CUSTOMER_ADDRESSES: Waiting for service(s) 'regions, address_types'...
[2020-08-27T07:51:10.968Z] INFO  customer-address-78b8ff95d7-brsz7-24/CUSTOMER_ADDRESSES: Service(s) 'regions, address_types' are available.
[2020-08-27T07:51:10.972Z] INFO  customer-address-78b8ff95d7-brsz7-24/REGISTRY: '$node' service is registered.
[2020-08-27T07:51:11.133Z] INFO  customer-address-78b8ff95d7-brsz7-24/$NODE: Service '$node' started.
Executing (default): SELECT 1+1 AS result
Executing (default): CREATE TABLE IF NOT EXISTS `customer_addresses` (`id` INTEGER NOT NULL auto_increment , `addressType` INTEGER NOT NULL, `customer` INTEGER NOT NULL, `province` INTEGER NOT NULL, `regency` INTEGER NOT NULL, `district` INTEGER NOT NULL, `subDistrict` INTEGER NOT NULL, `postalCode` INTEGER, `address` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `customer_addresses`
[2020-08-27T07:51:11.240Z] INFO  customer-address-78b8ff95d7-brsz7-24/CUSTOMER_ADDRESSES: Sequelize adapter has connected successfully.
[2020-08-27T07:51:11.273Z] ERROR customer-address-78b8ff95d7-brsz7-24/BROKER: Unable to start all services. Error: customer_addresses.belongsTo called with something that's not a subclass of Sequelize.Model
    at Function.<anonymous> (/app/node_modules/sequelize/lib/associations/mixin.js:93:13)
    at Service.started (/app/src/services/customer-address/customer_address.service.js:29:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
[Runner] customer_addresses.belongsTo called with something that's not a subclass of Sequelize.Model Error: customer_addresses.belongsTo called with something that's not a subclass of Sequelize.Model
    at Function.<anonymous> (/app/node_modules/sequelize/lib/associations/mixin.js:93:13)
    at Service.started (/app/src/services/customer-address/customer_address.service.js:29:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@1.0.0 start: `moleculer-runner src/services/**/*.service.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backend@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-27T07_51_11_304Z-debug.log

```

**Comment by icebob** [comment]
You can't pass complex objects between services (like Sequelize models), just what the transporter can serialize/deserialize. It can work during development because in this case there is no transporter.

**Comment by Mahardika23** [comment]
Ahh, I see, thanks for the heads up @icebob . Any suggestions on how to do relations/associations on a model? , currently struggling on doing relations, or as the docs says, i shall make my own adapter

**Comment by icebob** [comment]
Yeah, it's not a trivial part in the microservices world because if you access to a model of other services, it will be monolith and not microservices. By the way, moleculer-db is a single model/table service solution, if you need other complex solution you should write your service and using the sequelize models directly. Check @derekbar90 project maybe you find some ideas: https://github.com/derekbar90/catalyst

**Comment by Mahardika23** [comment]
Alright, will look into it, thanks !
