### ISSUE TITLE
Bug(registry): serialize a BigInt in settings

### ISSUE THREAD

**Issue by intech** [moleculerjs/moleculer#807]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

### Reproduce code snippet

```js
const { ServiceBroker } = require("moleculer");
const broker = new ServiceBroker();

broker.createService({
    name: "test",
    settings: {
      test: 16384n
    }
});

broker.start().catch(console.error);
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: v0.14.10
* NodeJS version: LTS
* Operating System: Linux

### Failure Logs
```
today at 01:51 [Runner] Do not know how to serialize a BigInt TypeError: Do not know how to serialize a BigInt
today at 01:51 at JSON.stringify (<anonymous>)
today at 01:51 at Object.safetyObject (/app/node_modules/moleculer/src/utils.js:350:26)
today at 01:51 at Registry.regenerateLocalRawInfo (/app/node_modules/moleculer/src/registry/registry.js:384:24)
today at 01:51 at /app/node_modules/moleculer/src/service-broker.js:457:19
today at 01:51 at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by intech** [comment]
Ref solution: https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-521460510
