### ISSUE TITLE
Error while run unit test on moleculer-cli generated project with es7 support

### ISSUE THREAD

**Issue by JasLin** [moleculerjs/moleculer#831]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

i am trying to make an [es7 template project](https://github.com/JasLin/moleculerjs-es7-template) with moleculer-cli generated project .now it can run with `npm run dev` without error, but it can't pass npm test
## Expected Behavior

it should pass unit test

here is es7 [products.service.js source code](https://github.com/JasLin/moleculerjs-es7-template/blob/master/services/products.service.js) 

## Failure Information
`npm test` with errors 
```js

  ● Test 'products' service › Test hooks › encountered a declaration exception

    ServiceSchemaError: Service name can't be empty! Maybe it is not a valid Service schema. Maybe is it not a service schema?

      4 | const DbMixin = require("../mixins/db.mixin");
      5 | 
    > 6 | @Service({
        | ^
      7 |       name: 'products',
      8 |       // constructOverride: false,
      9 |       // skipHandler: true,

      at Object.parseServiceSchema (../node_modules/moleculer/src/service.js:92:10)
      at new Service (../node_modules/moleculer/src/service.js:63:9)
      at new ProductsService (products.service.js:6:1)
      at new <anonymous> (../node_modules/moleculer-decorators/dist/index.js:128:9)
      at ServiceBroker.createService (../node_modules/moleculer/src/service-broker.js:801:14)
      at Suite.<anonymous> (../test/unit/services/products.spec.js:149:10)
      at Suite.<anonymous> (../test/unit/services/products.spec.js:146:2)
      at Object.<anonymous> (../test/unit/services/products.spec.js:9:1)
```
i try to debug it, found the error was begin from : 
products.spec.js
```js
...
describe("Test hooks", () => {
		const broker = new ServiceBroker({ logger: false });
		const createActionFn = jest.fn();
		broker.createService(TestService, { // <- error start from here, while it try to merge mock action to TestService Schema
			actions: {
				create: {
					handler: createActionFn
				}
			}
		});
...
}
```
and createService run into : 

```js
...
createService(schema, schemaMods) {
		let service;
		schema = this.normalizeSchemaConstructor(schema);
		if (Object.prototype.isPrototypeOf.call(this.ServiceFactory, schema)) {
			service = new schema(this, schemaMods); // <- run into here to new Decoratored Schema, but it with schemaMods, this is why it throws error , beacause `new service(broker, schemaMods)` will call parseServiceSchema, it will check name of schemaMods , but shemaMods don't have name properties. see bellow code . 
		} else {
			let s = schema;
			
			if (schemaMods)
				s = this.ServiceFactory.mergeSchemas(schema, schemaMods);
			console.log('s', s);
			service = new this.ServiceFactory(this, s);
		}
}
...
```
i notice that , moleculer-decorators return  Service as ([see ref](https://github.com/ColonelBundy/moleculer-decorators/blob/74b5b95bc040873720c9e1f39d9ccba5633ac34f/src/index.ts#L195))  :  
```js
return class extends parentService.constructor {
      constructor(broker, schema) { //  <- new schema(this, schemaMods) 
        super(broker, schema); // <- here, it will call `Moleculer.Service`, with params broker and schemaMods  
        this.parseServiceSchema(base);
      }
    };
  };
```

so it call `new Service (broker, schemaMods)` 

```js
class Service {

...
	constructor(broker, schema) {
		if (!isObject(broker))
			throw new ServiceSchemaError("Must set a ServiceBroker instance!");

		this.broker = broker;

		if (broker)
			this.Promise = broker.Promise;

		if (schema)
			this.parseServiceSchema(schema); // <- ran into here 
	}

	/**
	 * Parse Service schema & register as local service
	 *
	 * @param {Object} schema of Service
	 */
	parseServiceSchema(schema) {
		if (!isObject(schema))
			throw new ServiceSchemaError("The service schema can't be null. Maybe is it not a service schema?");

		this.originalSchema = _.cloneDeep(schema);

		if (schema.mixins) {
			schema = Service.applyMixins(schema);
		}

		if (isFunction(schema.merged)) {
			schema.merged.call(this, schema);
		} else if (Array.isArray(schema.merged)) {
			schema.merged.forEach(fn => fn.call(this, schema));
		}

		this.broker.callMiddlewareHookSync("serviceCreating", [this, schema]);

		if (!schema.name) { // <- error throws here
			
			console.error("Service name can't be empty! Maybe it is not a valid Service schema. Maybe is it not a service schema?", { schema });
			throw new ServiceSchemaError("Service name can't be empty! Maybe it is not a valid Service schema. Maybe is it not a service schema?", { schema });
		}
         ...
```

> i am confusing with [this line](https://github.com/moleculerjs/moleculer/blob/2f7d3d0d1a39511bc6bb9b71c6729326a3e8afad/src/service-broker.js#L799) in service-broker.js 
```js
service = new schema(this, schemaMods);  
```
beacause it will derectly trigger `parseServiceSchema()`whith `schemaMods`,  but `schemaMods` is not a normalization schema, it is part of schemas . so call `parseServiceSchema`  with `schemaMods` will allways fail? 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. git clone https://github.com/JasLin/moleculerjs-es7-template
2. npm i 
3. npm test

### Context

* Moleculer version: 0.14.11
* NodeJS version:  v13.14.0
* Operating System: ubuntu 18.04

### Failure Logs
```js

  ● Test 'products' service › Test hooks › encountered a declaration exception

    ServiceSchemaError: Service name can't be empty! Maybe it is not a valid Service schema. Maybe is it not a service schema?

      4 | const DbMixin = require("../mixins/db.mixin");
      5 | 
    > 6 | @Service({
        | ^
      7 |       name: 'products',
      8 |       // constructOverride: false,
      9 |       // skipHandler: true,

      at Object.parseServiceSchema (../node_modules/moleculer/src/service.js:92:10)
      at new Service (../node_modules/moleculer/src/service.js:63:9)
      at new ProductsService (products.service.js:6:1)
      at new <anonymous> (../node_modules/moleculer-decorators/dist/index.js:128:9)
      at ServiceBroker.createService (../node_modules/moleculer/src/service-broker.js:801:14)
      at Suite.<anonymous> (../test/unit/services/products.spec.js:149:10)
      at Suite.<anonymous> (../test/unit/services/products.spec.js:146:2)
      at Object.<anonymous> (../test/unit/services/products.spec.js:9:1)
```

**Comment by devalexandre** [comment]
this template is official ?
